#!/usr/bin/env ruby
# https://github.com/hanazuki/mackerel-plugin-smart
#
# MIT License
#
# Copyright (c) 2015 Kasumi Hanazuki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

require 'optparse'

PREFIX = 'SMART'

monitor_values = []
monitor_raws = []

OptionParser.new do |opt|
  opt.on('--value ATTRS', 'List of attribute IDs to monitor normalized value') {|v| monitor_values.push(*v.split(',').map(&:to_i)) }
  opt.on('--raw ATTRS', 'List of attribute IDs to monitor raw value') {|v| monitor_raws.push(*v.split(',').map(&:to_i)) }
  opt.parse!(ARGV)
end

# collect all hard drives
disks = Dir['/dev/sd*'].reject {|p| p =~ /\d\z/ }

disks.each do |disk_path|
  disk_name = File.basename(disk_path)

  now = Time.now.to_i
  smart_attrs = %x{smartctl -A #{disk_path}}.lines.map(&:strip).reject(&:empty?)
                .drop_while {|l| l !~ /^ID#/ }.drop(1).map {|l| l.split(/\s+/, 11) }

  # 0   1              2    3     4     5      6    7       8           9
  # ID# ATTRIBUTE_NAME FLAG VALUE WORST THRESH TYPE UPDATED WHEN_FAILED RAW_VALUE

  smart_attrs.each do |attr|
    attr_id = attr[0].to_i
    attr_name = attr[1]

    attr_value = attr[3]
    attr_raw = attr[9]

    if monitor_values.include?(attr_id)
      puts [[PREFIX, attr_name, disk_name].join(?.), attr_value, now].join(?\t)
    end

    if monitor_raws.include?(attr_id)
      puts [[PREFIX, attr_name, disk_name].join(?.), attr_raw, now].join(?\t)
    end
  end
end
